---
- name: provision a number of PV for the OCP
  hosts: nfs
  vars:
    base_dir: /srv/nfs
  tasks:
    - name: create dirs
      file:
        name: "{{ base_dir }}/{{ item }}"
        state: directory
        mode: 0777
        owner: nfsnobody
        group: nfsnobody
      with_sequence: count=100 format=pv%04d
    - name: add to exportfs
      lineinfile:
        path: /etc/exports.d/openshift-ansible.exports
        line: '"{{ base_dir }}/{{ item }} *(rw,root_squash)"'
      with_sequence: count=100 format=pv%04d
    - name: restart nfsd
      service:
        name: nfs
        state: restarted
