---
- name: provision a number of PV for the OCP
  hosts: nfs
  vars:
    base_dir: /srv/nfs
  tasks:
    - name: create dirs
      file:
        name: "{{ base_dir }}/{{ item }}"
        state: directory
        mode: 0777
        owner: nfsnobody
        group: nfsnobody
      with_sequence: count=50 format=pv%04d
    - name: add to exportfs
      lineinfile:
        path: /etc/exports.d/openshift-ansible.exports
        line: '"{{ base_dir }}/{{ item }} *(rw,root_squash)"'
      with_sequence: count=50 format=pv%04d
    - name: restart nfsd
      service:
        name: nfs
        state: restarted

- name: create pv inside openshift
  hosts: masters[0]
  vars:
     templates_dir: /root/config_files
     base_dir: /srv/nfs
     nfs_server: support1.f7ae.internal
     pv_size: 10Gi
  tasks:
    - name: create pv config files
      blockinfile:
        path: "{{ templates_dir }}/pv_create_{{ item }}"
        create: yes
        mode: 0400
        owner: root
        group: root
        block: |
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: "{{ item }}"
          spec:
            capacity:
              storage: "{{ pv_size }}"
            accessModes:
              - ReadWriteOnce
              - ReadWriteMany
            persistentVolumeReclaimPolicy: Retain
            nfs:
              path: "{{ base_dir }}/{{ item }}"
              server: "{{ nfs_server }}"
      with_sequence: count=50 format=pv%04d
    - name: ocp pv creation
      shell: /bin/oc create -f {{ templates_dir }}/pv_create_{{ item }}
      with_sequence: count=50 format=pv%04d
