---
- name: pv files remove
  hosts: masters[0]
  vars:
    templates_dir: /root/config_files
    base_dir: /srv/nfs
  tasks:
    - name: remove pv files
      file:
        path: "{{ templates_dir }}/pv_create_{{ item }}"
        state: absent
      with_sequence: count=50 format=pv%04d

- name: remove folders and entries in nfs server
  hosts: nfs
  vars:
    base_dir: /srv/nfs
  tasks:
    - name: remove dirs
      file:
        name: "{{ base_dir }}/{{ item }}/"
        state: absent
      with_sequence: count=50 format=pv%04d
    - name: remove from exports
      lineinfile:
        path: /etc/exports.d/openshift-ansible.exports
        line: '"{{ base_dir }}/{{ item }} *(rw,root_squash)"'
        state: absent
      with_sequence: count=50 format=pv%04d
    - name: restart nfsd
      service:
        name: nfs
        state: restarted

- name: remove logging metrics and registry files in nfs server
  hosts: nfs
  vars:
    base_dir: /srv/nfs
  tasks:
    - name: 
      file:
        name: "{{ base_dir }}/{{ item }}/"
        state: absent
      with_items:
        - registry
        - logging
        - metrics

